### ISSUE TITLE
Issue Resolved: How to Find Preferences in Finder

### ISSUE THREAD

**Issue by axcodex** [TissueEngineeringLab/MyoFInDer#67]
Subject: Issue Resolved: How to Find Preferences in Finder

Hi Jordan Blake,

I’m happy to let you know that the issue with finding "Preferences" in Finder has been resolved!

To access Finder Preferences, follow these simple steps:

Open Finder by clicking on its icon in the Dock.
In the top menu bar, click on Finder (next to the Apple logo).
From the dropdown menu, select Preferences.
The Preferences window will open, where you can customize Finder settings to your liking.
If you have any further questions or need additional help, feel free to reach out.

**Comment by WeisLeDocto** [comment]
Closing as this is unrelated to the project
